### ISSUE TITLE
Original lib

### ISSUE THREAD

**Issue by alex-oswald** [MatthewKing/WindowsFormsGenericHost#2]
Inspiration 😃 
https://github.com/alex-oswald/WindowsFormsLifetime

**Comment by MatthewKing** [comment]
Hey mate,

I'm really glad you posted this, because it has made me aware of a massive mistake I've made.

I did indeed take ideas and inspiration from your original project back in early 2020. I wanted to have a slightly different twist on the idea (support for ApplicationContext - which I see that your library now has). At the time, I was iterating on a few ideas for the API, and everything was a pre-release (hence the 0.1.0 and 0.2.0 version numbers). Once I hit 1.0.0, I planned to clean up the readme, and credit the projects I took inspiration from (ConsoleLifetime from Microsoft.Extensions.Hosting, and of course your library). However, I completely forgot about this project before it ever ended up hitting 1.0.0, and thus I never got around to properly crediting Microsoft.Extensions.Hosting and OswaldTechnologies.Extensions.Hosting.WindowsFormsLifetime. As mentioned above, this was a huge oversight on my part. I take full responsibility and I'm pretty embarrassed about it. Sorry.

My proposed fix is as follows:

1) Add the proper credit to Microsoft.Extensions.Hosting and OswaldTechnologies.Extensions.Hosting.WindowsFormsLifetime (as I should have done far earlier).
2) Add a recommendation to the readme that people use OswaldTechnologies.Extensions.Hosting.WindowsFormsLifetime instead, as it's a much more active project.

How does this sound to you?

Thanks again for bringing this to my attention, and my apologies for this stuff-up.

Cheers

**Comment by alex-oswald** [comment]
I don't think you made a mistake. The license I decided to pick was MIT. I simply just wanted to make that dotted line connection between repos. No need to change anything. I'm happy the project I started is inspiring! 😄 
🥂

**Comment by MatthewKing** [comment]
I think it's important to give credit where credit is due. This project was definitely inspired by yours, and I definitely regret that I didn't credit it sooner. You've done some great work on your project and it deserves credit. I'll update my readme once I get home and then close this issue once you've been credited appropriately. Cheers!
